title: 喵's StackHarbor
subtitle: Whisper to the World
#description: Everything that lives is designed to end.
description: 望むものなら<br>残さず輝ける自分らしさで
author: Alynx Zhou
email: alynx.zhou@gmail.com
language: zh_CN

baseURL: https://sh.alynx.xyz
rootDir: /
srcDir: srcs
docDir: docs
themeDir: aria
categoryDir: categories
tagDir: tags

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15
 
skipRender:
  - README.md

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

coffeescript:
  header: false
  bare: false

highlight:
  gutter: true
  hljs: true

search:
  enable: true
  path: search.json

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: false
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
