title: 喵's StackHarbor
subtitle: Whisper to the World
#subtitle: 搞 GNOME 只是个人兴趣，去 VA-11 调酒才是工作。
#description: Everything that lives is designed to end.
#description: 望むものなら<br>残さず輝ける自分らしさで
#description: 哀しみを知って<br>喜びを知った<br>弱さは君を変えて
#description: 全ての存在は滅びるようにデザインされている
#description: Whisper to the World
description: 将我漫天心血一一抛到银河
#description: 调制饮料，改变人生！
#description: 搞 GNOME 只是个人兴趣，去 VA-11 调酒才是工作。
author: Alynx Zhou
email: alynx.zhou@gmail.com
language: zh-Hans

# Those make up your site's full URL.
baseURL: https://sh.alynx.one
rootDir: /

# Those paths are relative to your site dir.
srcDir: srcs
docDir: docs
themeDir: themes/aria

# Those paths are relative to `docDir`.
# Set to `null` if you don't want them.
indexDir: .
archiveDir: archives
categoryDir: categories
tagDir: tags

# Those paths are relative to `srcDir`.
skipRender:
  - README.md

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

highlight:
  enable: false
  gutter: false
  hljs: true

search:
  enable: true
  path:
    - search/1.json
    - search/2.json
    - search/3.json
  page: search/index.html

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: true
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
