title: 喵's StackHarbor
subtitle: Whisper to the World
#description: Everything that lives is designed to end.
#description: 望むものなら<br>残さず輝ける自分らしさで
#description: 哀しみを知って<br>喜びを知った<br>弱さは君を変えて
description: 全ての存在は滅びるようにデザインされている
author: Alynx Zhou
email: alynx.zhou@gmail.com
language: zh-Hans

baseURL: https://sh.alynx.moe
rootDir: /
srcDir: srcs
docDir: docs
themeDir: aria

indexDir: /
archiveDir: archives
categoryDir: categories
tagDir: tags

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

skipRender:
  - README.md

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

coffeescript:
  header: false
  bare: false

highlight:
  gutter: true
  hljs: true

search:
  enable: true
  path: search.json

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: false
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
