# If a option has many sub-options, and it's optional, then give it a `enable` sub-option. If not optional, don't use `enable`.

menu:
  - name: home
    link: /
    icon: <i class="bi bi-house"></i>
  - name: archives
    link: archives/
    icon: <i class="bi bi-archive"></i>
  - name: categories
    link: categories/
    icon: <i class="bi bi-list-nested"></i>
  - name: tags
    link: tags/
    icon: <i class="bi bi-tags"></i>
  - name: Undefined Script Works!
    link: Undefined-Script-Works/
    icon: <i class="bi bi-terminal"></i>
  - name: 照片墙
    link: //gallery.alynx.one/
    icon: <i class="bi bi-images"></i>
  - name: blogroll
    link: blogroll/
    icon: <i class="bi bi-link-45deg"></i>
  # - name: 吐槽频道
  #   link: channel/
  #   icon: <i class="bi bi-volume-up"></i>
  - name: about
    link: about/
    icon: <i class="bi bi-person-bounding-box"></i>

# Transform your image to those favicons in https://realfavicongenerator.net/.
favicon:
  appleTouchIcon: favicons/apple-touch-icon.png
  androidChromeLarge: favicons/android-chrome-192x192.png
  medium: favicons/favicon-32x32.png
  small: favicons/favicon-16x16.png
  safariPinnedTab: favicons/safari-pinned-tab.svg
  androidManifest: favicons/site.webmanifest
  msBrowserConfig: favicons/browserconfig.xml
  fallback: favicon.ico

# Must be an array.
keywords:
  - Code
  - Music
  - Life
  - Arch Linux
  - GNOME
  - JavaScript
  - ARIA
  - Hikaru

# https://creativecommons.org/licenses/
# by | by-sa | by-nd | by-nc | by-nc-sa | by-nc-nd
creativeCommons: by-nc-nd

# Available: atom-one-dark | atom-one-light | tomorrow-night-blue | tomorrow-night-bright | solarized-dark | solarized-light
highlight: atom-one-dark

# Pinned message in home page.
pinnedMessage: <div class="alert-blue">读了某些文章觉得很有趣或者很有收获？<strong>我很想知道你对我博客的看法！</strong>如果方便请务必到 <a href="/about/">关于</a> 页面留下一条评论！</div>

# Custom info in footer.
customInfo: 托管于 <i class="bi bi-github"></i><a href="https://pages.github.com/" target="_blank" rel="noreferrer noopener">GitHub Pages</a> 和 <i class="bi bi-triangle-fill"></i><a href="https://vercel.com/" target="_blank" rel="noreferrer noopener">Vercel</a>

# Select all your webfont in a CDN like Google Fonts, and then copy `href` property in the `<link>` tag, like `link: //fonts.googleapis.com/css?family=Lato|Roboto+Condensed|Skranji|Ubuntu|Ubuntu+Mono`.
# Then set different fonts to different parts here.
customFont:
  enable: false
  link: //fonts.googleapis.com/css?family=Lato|Roboto+Condensed|Skranji|Ubuntu|Ubuntu+Mono
  all: Ubuntu
  title: Roboto Condensed
  subtitle: Roboto Condensed
  main: Ubuntu
  code: Ubuntu Mono

#avatar: images/FutureGazerSmall.webp
#avatar: images/MisakaMikotoSmall.png
avatar: images/Mikoto_Karon_White.webp

#logo: images/logo.webp
#logo: images/sticker_arch.webp
logo: images/I-love-Arch.webp

# Theme color.
# Need quote to prevent `#` from comment.
color: "#33363b"

googleVerification: VmX1m6eF3rZhAf1iR5DhqrbiF_5se-s902W14pPryQk

since: 2016

search: true

# `left`, `right`, `false`
sidebar: right

animate: false

busuanzi: true

# If you want ARIA generate excerpt, set it to the length you want. If you don't, leave it blank.
# Recommend to place `<!--more-->` to where you want to stop excerpt in content instead of use this option.
# Example: `autoExcerpt: 200`, use first 200 chars in post content as excerpt.
autoExcerpt: 150

# If you want to use MathJax, first fill a CDN link like `cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-MML-AM_CHTML`, then set `enable: true`.
# And set front-matter `mathjax: true` to the page you want to use it.
# You can also set `global: true` here to load MathJax in all pages.
# But it's not recommended because MathJax sources are too large, that's why ARIA doesn't contain them and ask for CDN.
mathjax:
  enable: false
  global:
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML

# Note: `fontAwesome.loader` is `fontawesome.min.js`. `busuanzi` is `busuanzi.pure.mini.js`.
# If you don't know what you are doing, don't change it.
libCDN:
  enable: false
  bootstrapIcons:
    css:
    woff2:
    woff:
  normalize:
  busuanzi:
  highlight: //cdn.bootcdn.net/ajax/libs/highlight.js/10.1.2/highlight.min.js
  clipboard: //cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.6/clipboard.min.js
  # Don't use camelCase for hljs theme CSS files,
  # because they need to keep the same as highlight values.
  atom-one-dark:
  atom-one-light:
  solarized-dark:
  solarized-light:

social:
  enable: true
  links:
    - name: E-Mail
      link: mailto:alynx.zhou@gmail.com
      icon: <i class="bi bi-envelope"></i>
    - name: GitHub
      link: https://github.com/AlynxZhou/
      icon: <i class="bi bi-github"></i>
    - name: Telegram
      link: https://t.me/AlynxZhou/
      icon: <i class="bi bi-telegram"></i>
    - name: Bilibili
      link: https://space.bilibili.com/10034969/
      icon: <i class="bi bi-film"></i>
    - name: Steam
      link: https://steamcommunity.com/id/AlynxZhou/
      icon: <i class="bi bi-steam"></i>

blogroll:
  enable: true
  links:
    - name: Arch Linux 星球
      link: https://planet.archlinuxcn.org/
      icon: <i class="bi bi-link-45deg"></i>
    - name: H-el-ical//
      link: https://h-el-ical.com/
      icon: <i class="bi bi-link-45deg"></i>
    - name: Bo Lin's Blog
      link: https://berlin-98.github.io/
      icon: <i class="bi bi-link-45deg"></i>
    - name: Meow's Blog
      link: https://lrscy.github.io/
      icon: <i class="bi bi-link-45deg"></i>
    - name: LGiki's Blog
      link: https://lgiki.net/
      icon: <i class="bi bi-link-45deg"></i>
    # - name: HackGhost's Blog
    #   link: http://hackghost.com/
    #   icon: <i class="bi bi-link-45deg"></i>
    - name: Art_Chen's Blog
      link: http://chenxy.moe/
      icon: <i class="bi bi-link-45deg"></i>
    - name: Farseerfc 的小窝
      link: https://farseerfc.me/
      icon: <i class="bi bi-link-45deg"></i>
    - name: 滑稽仓库
      link: http://huaji.store/
      icon: <i class="bi bi-link-45deg"></i>
    # - name: 鸡腿工坊
    #   link: https://jitui.moe/
    #   icon: <i class="bi bi-link-45deg"></i>
    - name: Sqyon's Blog
      link: https://sqyon.cc/
      icon: <i class="bi bi-link-45deg"></i>
    - name: 高渐离の屋
      link: https://blog.gaojianli.me/
      icon: <i class="bi bi-link-45deg"></i>
    - name: 约伊兹的萌狼乡手札
      link: https://blog.yoitsu.moe/
      icon: <i class="bi bi-link-45deg"></i>
    - name: Nichi Yorozuya
      link: https://nichi.co/
      icon: <i class="bi bi-link-45deg"></i>
    - name: 惠狐之书
      link: https://blog.megumifox.com/
      icon: <i class="bi bi-link-45deg"></i>
    # - name: 初等記憶體
    #   link: https://axionl.me/
    #   icon: <i class="bi bi-link-45deg"></i>
    # - name: OriginCode 札記
    #   link: https://originco.de/
    #   icon: <i class="bi bi-link-45deg"></i>

comment:
  enable: true
  issue:
    enable: true
    user: AlynxZhou
    repo: stackharbor
    perPage: 10
  disqusShortName: stackharboralynxxyz

reward:
  enable: true
  message: 既然看了喵写的文章，不打算投喂一下再走吗？哼！
  weChatPayQRCode: images/WeChatPay.webp
  aliPayQRCode: images/AliPay.webp
  # bitCoinQRCode: images/BitCoin.png
